### PR TITLE
Allow toBeRdfIsomorphic to take datasets

### PR DESCRIPTION
**Pull request by thewilkybarkid**
Expands toBeRdfIsomorphic to take iterables rather than just arrays, so it can be used for datasets etc.

### CODE REVIEW

**Comment by rubensworks** [comment]
Thanks!
@thewilkybarkid Do you have any other PRs planned? Or shall I make a new release of this?

**Comment by thewilkybarkid** [comment]
Pretty sure this is it, just implementing these on https://github.com/libero/article-store (PR opened there shortly).

**Comment by rubensworks** [comment]
Cool :-)
Released as 1.5.0.

**Comment by thewilkybarkid** [comment]
https://github.com/libero/article-store/pull/204

**Pull request merged**
